[package]
name = "storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
shared = { path = "../shared" }

anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

rusqlite = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tempfile = "3.8"

[lib]
name = "storage"
path = "src/lib.rs"
